### ISSUE TITLE
opentelemetry-collector returning not found

### ISSUE THREAD

**Issue by Xosmond** [jgaskins/opentelemetry#1]
Hi. Thanks for this repository.

I tested and works smoothly with ui.honeycomb.io.

But I tried to test it using:

```
otel/opentelemetry-collector:0.35.0
```

And UI's:
```
openzipkin/zipkin
jaegertracing/all-in-one
```

When debugging I see this make a request to `/v1/traces` and `opentelemetry-collector` returns not found.

Do you know if this should work out of the box or this is not compatible or we should do something else?

Thanks

**Comment by jgaskins** [comment]
Interesting, `/v1/traces` is [the canonical OTLP/HTTP endpoint](https://github.com/open-telemetry/opentelemetry-specification/blob/90d9aab8a871db4954831e8447eb325ef020a80c/specification/protocol/otlp.md#otlphttp-request) and using this shard with the collector worked for me.

Can you paste the `receivers` config from your `collector-config.yaml`?

**Comment by jgaskins** [comment]
Also, to be perfectly transparent, I'm still relatively new to OTel so it's very possible I've overlooked something along the way.

**Comment by Xosmond** [comment]
@jgaskins Hi man! I was debugging. This `otel-collector` thing is hard to debug, it does not log anything and just return 404 when fails. Anyway I found the issue. Its because the request is sending as header: `content-type:application/protobuf` and it expects `content-type:application/x-protobuf`

I wonder if the other services support the "x-" change.

**Comment by jgaskins** [comment]
Oh, interesting. This shard [_does_ send `content-type: application/x-protobuf`](https://github.com/jgaskins/opentelemetry/blob/ca32f4a72f0e1fc67d6f2e3a5f4ee90176b08e0e/src/exporter.cr#L112), but it's something I discovered later and you may have the old code from before that change.

If you run `shards update opentelemetry` to get the latest version of the code (I haven't done any actual releases yet, so it's all just on the `main` branch for now), does this still happen?

**Comment by jgaskins** [comment]
I completely forgot I had the exact same problem when using it with the collector. Honeycomb only checks that the `content-type` header contains `protobuf` rather than an exact match, so it worked just fine, but the collector is a bit more strict.

**Comment by Xosmond** [comment]
Ah makes sense. I added the `branch: main` on the shard dependency and it got updated.

Now I got another issue but better to open a new issue to not make noise here.

Thanks @jgaskins.
